sudo: required
services: 
  - docker

before_install:
  - docker build -t hemanth09/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true hemanth09/docker-react npm run test -- --coverage